import { useCallback, useRef, useState } from 'react';
import {
  Box,
  Button,
  Card,
  Dialog,
  Flex,
  Grid,
  Inline,
  Label,
  Select,
  Spinner,
  Stack,
  Text,
  TextArea,
} from '@sanity/ui';
import { CheckmarkCircleIcon, ResetIcon } from '@sanity/icons';
import type { AssetFromSource, AssetSourceComponentProps } from 'sanity';
import type { ExecutionOutput, ExecutionStatus } from '@uselamina/sdk';
import { useLamina } from '../lib/LaminaContext.js';
import type { GeneratedOutput, GenerationState } from '../types.js';

const MODALITIES = [
  { value: '', label: 'Auto-detect' },
  { value: 'image', label: 'Image' },
  { value: 'video', label: 'Video' },
] as const;

function toGeneratedOutput(out: ExecutionOutput): GeneratedOutput | null {
  if (out.status !== 'completed' || !out.value || typeof out.value !== 'string') {
    return null;
  }
  return {
    id: out.id,
    type: out.type,
    url: out.value,
    mimeType: out.mimeType ?? null,
    label: out.label,
    dimensions: out.dimensions ?? null,
    durationSeconds: out.durationSeconds ?? null,
  };
}

function progressFromStatus(status: ExecutionStatus): number | null {
  switch (status.status) {
    case 'queued':
      return 10;
    case 'running':
      return 50;
    case 'completed':
      return 100;
    case 'failed':
      return null;
    default:
      return null;
  }
}

export function GenerateDialog(props: AssetSourceComponentProps) {
  const {
    assetType: rawAssetType,
    selectionType,
    onSelect,
    onClose,
  } = props;

  // Normalize assetType to our two known values
  const assetType = rawAssetType === 'image' ? 'image' : 'file';
  const { client } = useLamina();
  const [brief, setBrief] = useState('');
  const [modality, setModality] = useState('');
  const [state, setState] = useState<GenerationState>({
    status: 'idle',
    runId: null,
    outputs: [],
    error: null,
    progress: null,
  });

  const abortRef = useRef<AbortController | null>(null);

  const handleGenerate = useCallback(async () => {
    if (!brief.trim()) return;

    abortRef.current?.abort();
    const abort = new AbortController();
    abortRef.current = abort;

    setState({
      status: 'generating',
      runId: null,
      outputs: [],
      error: null,
      progress: 10,
    });

    try {
      const resolvedModality =
        modality || (assetType === 'file' ? 'video' : 'image');

      const createResult = await client.content.create({
        brief: brief.trim(),
        modality: resolvedModality,
      });

      if (abort.signal.aborted) return;

      const runId = createResult.data.runId;
      if (!runId) {
        // needs-input case: the selected app requires more params
        const missing = createResult.data.needsInput;
        setState((prev) => ({
          ...prev,
          status: 'failed',
          error: missing
            ? `More info needed: ${missing.message}`
            : 'No run was started. Try a more specific brief.',
        }));
        return;
      }

      setState((prev) => ({ ...prev, runId }));

      const result = await client.runs.wait(runId, {
        intervalMs: 3000,
        onPoll(status) {
          if (abort.signal.aborted) return;
          setState((prev) => ({
            ...prev,
            progress: progressFromStatus(status),
          }));
        },
      });

      if (abort.signal.aborted) return;

      if (result.data.status === 'failed') {
        setState((prev) => ({
          ...prev,
          status: 'failed',
          error: result.data.errorMessage || 'Generation failed.',
          progress: null,
        }));
        return;
      }

      const outputs = result.data.outputs
        .map(toGeneratedOutput)
        .filter((o): o is GeneratedOutput => o !== null);

      setState({
        status: 'completed',
        runId,
        outputs,
        error: null,
        progress: 100,
      });
    } catch (err) {
      if (abort.signal.aborted) return;
      setState((prev) => ({
        ...prev,
        status: 'failed',
        error: err instanceof Error ? err.message : 'Unknown error',
        progress: null,
      }));
    }
  }, [brief, modality, assetType, client]);

  const handleSelectOutput = useCallback(
    (output: GeneratedOutput) => {
      const asset: AssetFromSource = {
        kind: 'url',
        value: output.url,
        assetDocumentProps: {
          originalFilename: `lamina-${state.runId ?? 'gen'}-${output.id}.${
            output.mimeType?.split('/')[1] || 'png'
          }`,
          source: {
            name: 'lamina',
            id: state.runId ?? output.id,
            url: `https://app.uselamina.ai/runs/${state.runId ?? output.id}`,
          },
          description: brief,
          creditLine: 'Generated by Lamina',
        } as AssetFromSource['assetDocumentProps'],
      };
      onSelect([asset]);
    },
    [state.runId, brief, onSelect],
  );

  const handleReset = useCallback(() => {
    abortRef.current?.abort();
    setState({
      status: 'idle',
      runId: null,
      outputs: [],
      error: null,
      progress: null,
    });
  }, []);

  return (
    <Dialog
      id="lamina-generate"
      header="Generate with Lamina"
      onClose={onClose}
      width={2}
      open
    >
      <Box padding={4}>
        <Stack space={4}>
          {/* Brief input */}
          <Stack space={2}>
            <Label size={1}>Describe what you need</Label>
            <TextArea
              value={brief}
              onChange={(e) => setBrief(e.currentTarget.value)}
              placeholder="Product photo of white sneakers on marble surface, lifestyle aesthetic"
              rows={3}
              disabled={state.status === 'generating'}
            />
          </Stack>

          {/* Modality selector */}
          <Stack space={2}>
            <Label size={1}>Output type</Label>
            <Select
              value={modality}
              onChange={(e) => setModality(e.currentTarget.value)}
              disabled={state.status === 'generating'}
            >
              {MODALITIES.map((m) => (
                <option key={m.value} value={m.value}>
                  {m.label}
                </option>
              ))}
            </Select>
          </Stack>

          {/* Action buttons */}
          {state.status === 'idle' || state.status === 'failed' ? (
            <Button
              text="Generate"
              tone="primary"
              onClick={handleGenerate}
              disabled={!brief.trim()}
            />
          ) : null}

          {/* Error */}
          {state.status === 'failed' && state.error ? (
            <Card padding={3} radius={2} tone="critical">
              <Text size={1}>{state.error}</Text>
            </Card>
          ) : null}

          {/* Progress */}
          {state.status === 'generating' ? (
            <Card padding={4} radius={2} tone="primary">
              <Flex align="center" gap={3}>
                <Spinner />
                <Stack space={2}>
                  <Text size={1} weight="medium">
                    Generating...
                  </Text>
                  {state.progress !== null ? (
                    <Text size={1} muted>
                      {state.progress}% complete
                    </Text>
                  ) : null}
                </Stack>
              </Flex>
            </Card>
          ) : null}

          {/* Results */}
          {state.status === 'completed' && state.outputs.length > 0 ? (
            <Stack space={3}>
              <Label size={1}>Generated assets</Label>
              <Grid columns={state.outputs.length > 1 ? 2 : 1} gap={3}>
                {state.outputs.map((output) => (
                  <Card
                    key={output.id}
                    padding={2}
                    radius={2}
                    border
                    style={{ cursor: 'pointer' }}
                  >
                    <Stack space={2}>
                      {output.type === 'video' ? (
                        <video
                          src={output.url}
                          controls
                          style={{
                            width: '100%',
                            borderRadius: 4,
                            maxHeight: 240,
                            objectFit: 'contain',
                          }}
                        />
                      ) : (
                        <img
                          src={output.url}
                          alt={output.label}
                          style={{
                            width: '100%',
                            borderRadius: 4,
                            maxHeight: 240,
                            objectFit: 'contain',
                          }}
                        />
                      )}
                      <Text size={1} muted>
                        {output.label}
                      </Text>
                      <Inline space={2}>
                        <Button
                          text="Use this"
                          tone="positive"
                          icon={CheckmarkCircleIcon}
                          onClick={() => handleSelectOutput(output)}
                          fontSize={1}
                          padding={2}
                        />
                      </Inline>
                    </Stack>
                  </Card>
                ))}
              </Grid>

              {/* Regenerate */}
              <Inline space={2}>
                <Button
                  text="Regenerate"
                  tone="default"
                  icon={ResetIcon}
                  mode="ghost"
                  onClick={handleReset}
                  fontSize={1}
                />
              </Inline>
            </Stack>
          ) : null}
        </Stack>
      </Box>
    </Dialog>
  );
}
